remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme

title: "Innovations and Opportunities"
description: "SIGCSE 2022 Affiliated Event by the SIGCSE Committee on Computing Education in Liberal Arts Colleges"

show_downloads: false
